### ISSUE TITLE
I would like a way to restrict the websites where the plugin is active

### ISSUE THREAD

**Issue by ken-aus** [taterboom/PromptSnippets#19]
Hi,

I love this plugin but I am hitting an issue where it activates on some inappropriate websites, and popups get in the way of what I'm trying to do. For example, it always activates on my white-labelled HighLevel CRM site, and the popups get in the way of data entry. As a result, I leave the plugin deactivated most of the time to avoid this issue, and only turn it on when I use ChatGPT or Claude.

I would love a setting to list the websites where the plugin should activate and have it remain inactive on all other websites. For example, I would set that list to only:

chat.openai.com
poe.com

and then the plugin would behave perfectly, only activating when I need it.

Thanks.

**Comment by taterboom** [comment]
Thank you for reaching out and sharing your feedback regarding the PromptSnippets browser plugin. 

Currently, the plugin is designed to activate on all websites by default and can be deactivated in the settings panel of the plugin.

In the upcoming update, I plan to introduce a new feature where you can configure a list with wildcard of websites where PromptSnippets should activate, while remaining inactive on all other websites. 

such as:
- poe.com
- *.openai.com

or just * for all websites.
